# -*- coding: utf-8 -*-
"""data_register.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nw4PSo1XG_TEs_xC9LErcHgaknuSlsND
"""

from huggingface_hub import notebook_login
notebook_login()

from datasets import load_dataset

# Load local CSV file
dataset = load_dataset(
    "csv",
    data_files="tourism.csv"
)

# Push dataset to Hugging Face
dataset.push_to_hub("Amyd64/tourism-package-dataset")

print("✅ Dataset uploaded successfully!")