# -*- coding: utf-8 -*-
"""prep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4VBPtrZVR28u97f6w75dA3Thfa9HTyo
"""

# ===============================
# LOAD DATA FROM HUGGING FACE
# ===============================

print("📥 Loading dataset from Hugging Face...")

from datasets import load_dataset

# Load dataset using your Hugging Face repo ID
dataset = load_dataset("Amyd64/tourism-package-dataset")

# Convert dataset to pandas DataFrame
df = dataset["train"].to_pandas()

# Display basic information
print("✅ Dataset loaded successfully!")
print("Shape of dataset:", df.shape)

# Show first 5 rows
print("\nSample Data:")
print(df.head())

"""- The dataset was successfully loaded from the Hugging Face repository and
converted into a pandas DataFrame.
- It contains 4128 rows and 21 columns, representing customer details and interaction data.
- A preview of the dataset confirms that the data is properly structured and ready for preprocessing.
"""

# ===============================
# DATA CLEANING
# ===============================

print("\n🧹 Cleaning dataset...")

# Remove duplicate rows
df = df.drop_duplicates()

# Handle missing values using forward fill
df = df.fillna(method="ffill")

# Drop unnecessary column if exists
if "CustomerID" in df.columns:
    df = df.drop(columns=["CustomerID"])

print("✅ Data cleaning completed!")
print("Shape after cleaning:", df.shape)

"""The dataset was cleaned by removing duplicate records, handling missing values using forward fill, and dropping unnecessary columns such as CustomerID.
After cleaning, the dataset contains 4128 rows and 20 columns, ensuring improved data quality for further processing.
"""

# ===============================
# FEATURE SELECTION
# ===============================

print("\n🎯 Selecting features and target variable...")

# Define target variable
target = "ProdTaken"

# Numerical features
numeric_features = [
    'Age', 'CityTier', 'NumberOfPersonVisiting',
    'PreferredPropertyStar', 'NumberOfTrips',
    'NumberOfChildrenVisiting', 'MonthlyIncome',
    'PitchSatisfactionScore', 'NumberOfFollowups',
    'DurationOfPitch'
]

# Categorical features
categorical_features = [
    'TypeofContact', 'Occupation', 'Gender',
    'MaritalStatus', 'Designation',
    'ProductPitched', 'Passport', 'OwnCar'
]

# Create feature matrix (X) and target (y)
X = df[numeric_features + categorical_features]
y = df[target]

print("✅ Feature selection completed!")
print("Feature shape:", X.shape)
print("Target shape:", y.shape)

"""Relevant features and the target variable were selected, resulting in 18 input features and 4128 target values for model training."""

# ===============================
# TRAIN-TEST SPLIT
# ===============================

print("\n🔀 Splitting dataset into train and test sets...")

from sklearn.model_selection import train_test_split

# Split data (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("✅ Data split completed!")
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

"""The dataset was split into training (80%) and testing (20%) sets, resulting in 3302 training samples and 826 testing samples.

The dataset was split into training and testing sets with 3302 training samples and 826 testing samples for model evaluation.
"""

from huggingface_hub import notebook_login
notebook_login()

dataset_dict.push_to_hub("Amyd64/tourism-processed-dataset")

"""The processed dataset was successfully uploaded to the Hugging Face Hub, making it available for future use in model training and deployment.

In this phase, the dataset was loaded from Hugging Face, cleaned, and preprocessed. Relevant features and the target variable were selected, followed by splitting the data into training and testing sets. The processed datasets were saved locally and uploaded to the Hugging Face Hub for reuse in the MLOps pipeline.
"""