# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z2U8ljNSrVFr-oCIs5Rqw6ozrlVZMiSO

## Importing Important Libraries
"""

!pip install mlflow

# All imports at top (final version)
import pandas as pd
from datasets import load_dataset
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
import mlflow
import joblib
import os

"""## Load Dataset from Hugging Face"""

print("📥 Loading dataset from Hugging Face...")

dataset = load_dataset("Amyd64/tourism-processed-dataset")

train_df = dataset["train"].to_pandas()
test_df = dataset["test"].to_pandas()

print("✅ Dataset loaded successfully!")
print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

"""The processed dataset was successfully loaded from Hugging Face, with 3302 training samples and 826 testing samples ready for model building.

# Feature & Target Separation
"""

print("\n🎯 Separating features and target...")

X_train = train_df.drop("ProdTaken", axis=1)
y_train = train_df["ProdTaken"]

X_test = test_df.drop("ProdTaken", axis=1)
y_test = test_df["ProdTaken"]

print("✅ Feature-target separation completed!")
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

"""The dataset was successfully split into input features and the target variable for model training.

# Data Preprocessing (Encoding)
"""

print("\n🔄 Encoding categorical features...")

# Convert categorical → numerical
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

# Align columns (VERY IMPORTANT)
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

print("✅ Encoding completed!")
print("Encoded X_train shape:", X_train.shape)
print("Encoded X_test shape:", X_test.shape)

"""- Categorical variables were encoded into numerical format, and feature columns were aligned for consistent model training.
- Feature alignment ensures both training and testing datasets have identical columns after encoding.

# Model Training + Hyperparameter Tuning
"""

print("\n⚙️ Training model with hyperparameter tuning...")

# Define parameter grid
param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [5, 10]
}

# Initialize model
model = RandomForestClassifier(random_state=42)

# Grid Search
grid = GridSearchCV(model, param_grid, cv=3, n_jobs=-1)

# Train model
grid.fit(X_train, y_train)

# Best model
best_model = grid.best_estimator_

print("✅ Model training completed!")
print("Best Parameters:", grid.best_params_)

"""The model was successfully trained using hyperparameter tuning, and the optimal parameters (max_depth=10, n_estimators=200) were selected.

# Experiment Tracking (MLflow)
"""

print("\n📊 Logging experiment with MLflow...")

# Set experiment
mlflow.set_experiment("tourism-mlops")

with mlflow.start_run():

    # Log best parameters
    mlflow.log_params(grid.best_params_)

    # Predictions
    y_pred = best_model.predict(X_test)

    # Accuracy
    accuracy = accuracy_score(y_test, y_pred)

    # Log metric
    mlflow.log_metric("accuracy", accuracy)

    print(f"✅ Accuracy: {accuracy:.4f}")

"""The model parameters and performance were successfully logged using MLflow, achieving an accuracy of 0.8789.

## Save Model
"""

import joblib
import os

print("\n💾 Saving model...")

# Create folder if not exists
os.makedirs("../models", exist_ok=True)

# Save model
model_path = "../models/model.pkl"
joblib.dump(best_model, model_path)

print("✅ Model saved successfully!")

"""The trained model was successfully saved locally for future use and deployment.

# Upload Model to Hugging Face
"""

from huggingface_hub import notebook_login
notebook_login()

from huggingface_hub import create_repo, upload_file

print("\n☁️ Uploading model to Hugging Face...")

repo_id = "Amyd64/tourism-model"

# Create model repo if not exists
create_repo(repo_id, repo_type="model", exist_ok=True)

# Upload model file
upload_file(
    path_or_fileobj="../models/model.pkl",
    path_in_repo="model.pkl",
    repo_id=repo_id,
    repo_type="model"
)

print("✅ Model uploaded successfully!")

"""The trained model was successfully uploaded to the Hugging Face Model Hub for deployment and reuse.

In this phase, the processed dataset was used to train a machine learning model with hyperparameter tuning. Model performance was evaluated and logged using MLflow, and the best-performing model was saved and uploaded to the Hugging Face Model Hub for deployment.
"""